language: go
go:
- 1.8.x
before_deploy:
- echo 'Pre deployment to Heroku'
deploy:
  provider: heroku
  api_key:
    secure: ksZ46r1yrh3bELc418+kWcuXpO9OaD3DhN9omEog0Q7Ak9bYJX0KuheslRtzdkXRWk/Kw8Ct0CZ6uNb3p8WwXY4BxapWXJqZxur/SqC3iw2f15Q141UFcSm7JtJ6l7Ldy6VVupuHUmB12mCvkrJYWMaqnGRvV+QUo+fUPHIEUTO8JT60T8pK8WipMYCgVVYE+iUyMllFW/b4PG4Rt1HSZmk997dOQfAGsFHuGkakJC0AW0q8iRpcoztykyem521HKe1hkA07cBy4q6bOH2IugIGjzxAVSHPsPOZicZQQjCJ7p5LkR2xN4nCQhlGYdQM3T1oxEM7PiXTqLQ4jD/5KbOiLSpuJN0Z48eWD1bHjGhyFbGTfjv/hF4nply8FBO/nhaZJwfVI9EFB075agl5QzDu1zJ8BVNFler2ivdwlINn1TJUqK2YvWfmhhtlZ+Gal27Y3+vZ6U5h1t3vW26tBTMHkED+mir+6SHGzr051gb24bdHUlK0oX0A0b1/N2e3a7GPaLJfZb19tC2iYMm2v7xn0fmoysm6mCpHK5z+HYEKUPmRptjEDozZ2eLg9kmht0WKcnXFpWi6c72xVDNfrBWUDDTsrx+3Fr6LaaaXuuLl0JJGrhllpXdTuNnm6tCcNYKLJ4HFhVQeCWv3NFbMkl9+Vh92T8s4ylqH3uoIsTMM=
  app: soapigo
  on:
    repo: nikhosagala/soapi
  auto_cleanup: true
notifications:
  email: false
