language: go
go:
- 1.10.x
before_script:
- psql -c "create database soapi;" -U postgres
- psql -c "create user soapiuser with password 'soapipass';" -U postgres
- psql -c "alter user postgres with password 'postgres';" -U postgres
services:
- postgresql
before_deploy:
- echo 'Pre deployment to Heroku'
deploy:
  provider: heroku
  api_key:
    secure: Shk9GMk0f7qc3jyZ/TRv8DcvGqEfO0ftxmRPsKW4jeH+BqamLbcZknB3SXwq7L4/NkNtUBVk+VG+BMUePuWyZnWHCDCmJh8HT915n/NG9cjEamJ1Wh7xqdxGXc2SJeMPbgeyePsQ4KAXSbCupInMazOHSDeFIed21GhTaoqUgQ+oDQ6dV59U3iLwDjcOrkAtYRjewlkEZpN5EgRCxSrRWi/PL1vK9zUDGiuHXuMOQZNuHdRKQzAgVIELvUI+OsvYTG98vCgcc9CUUYww9sYiyA1ke2PxXigfxbzvHVmKTp45L3gJScySn9OnrB96CThqEtypcI/VphB38uRhUsUKPA4Nhi6lQPKkl4wvOYBg3Xp2U9++w3Zl8OxhwFJ0bL/M6qYVxc2WMvbur7C4L/6plJ7QOzXfm7DjQTxjsAH577aFLD0HZ8dRu/byfiOsLMOhV3ZbYGgTV3lolqgxRP671aA3i+FtBYNwGnkXPubfFp8sskYpGc+2SbGsLOP/2OE/XOvb7Mt3m6hVhxzXN0rQoFnoh+YGw5Mf42/LLvyH3q5LTlURMHAgiv/qUHmRSLY3GgLe8abkMQ7sc8ihAtBJJzyUSEqqJmYA4tmKvjR34Bu2iuAGGhrNXvRPBqDniFr0FhSwA/NOmPF3xqAXjA+GiiAGX6ANReTAJp+GMf9xw6s=
  app: soapigo
  on:
    repo: nikhosagala/soapi
notifications:
  email: false
