version: '3'
services:
  db:
    image: postgres:10.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: soapi
      POSTGRES_USER: soapiuser
      POSTGRES_PASSWORD: soapipass